[package]
name = "tree-sitter-cloudflare"
description = "Cloudflare rules language grammar for the tree-sitter parsing library"
version = "0.0.1"
authors = ["nfowl", "Colin Bendell <colin@bendell.ca>"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "cloudflare"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/colinbendell/tree-sitter-cloudflare"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.11"
anyhow = "1.0"
reqwest = { version = "0.13", features = ["blocking"] }
